export const books = [
  {
    title: "Corte de Espinhos e Rosas",
    synopsis:
      "Feyre Archeron é arrastada para o mundo das Fae após matar um lobo que era mais do que parecia.",
    language: "Português",
    price: 39.9,
    ISBN: "978-0-06-231123-8",
    page_count: 432,
    release_date: "2015-05-05",
    stock_quantity: 25,
    image_url:
      "https://m.media-amazon.com/images/I/81qMLIEhMYL._AC_UF1000,1000_QL80_.jpg",
    authors: ["Sarah J. Maas"],
    genres: ["Fantasia", "Romance", "Aventura"],
    publishers: ["Galera Record"],
  },

  {
    title: "Corte de Névoa e Fúria",
    synopsis:
      "Depois de sobreviver aos horrores de Amarantha, Feyre precisa enfrentar as consequências de suas escolhas e a complexidade de seu novo papel no mundo das Fae.",
    language: "Português",
    price: 49.9,
    ISBN: "978-0-06-231126-9",
    page_count: 624,
    release_date: "2016-05-03",
    stock_quantity: 30,
    image_url:
      "https://m.media-amazon.com/images/I/81WJEn8imXL._AC_UF1000,1000_QL80_.jpg",
    authors: ["Sarah J. Maas"],
    genres: ["Fantasia", "Romance", "Drama"],
    publishers: ["Galera Record"],
  },
  {
    title: "Corte de Asas e Ruína",
    synopsis:
      "Feyre retorna à Corte Primaveril como espiã, enquanto prepara o terreno para uma guerra que ameaça destruir o mundo dos humanos e das Fae.",
    language: "Português",
    price: 54.9,
    ISBN: "978-0-06-231128-3",
    page_count: 699,
    release_date: "2017-05-02",
    stock_quantity: 20,
    image_url:
      "https://m.media-amazon.com/images/I/81aZyTrwZjL._AC_UF1000,1000_QL80_.jpg",
    authors: ["Sarah J. Maas"],
    genres: ["Fantasia", "Romance", "Guerra"],
    publishers: ["Galera Record"],
  },
  {
    title: "Clean Code",
    synopsis:
      "Um guia prático para escrever códigos legíveis, mantíveis e de alta qualidade.",
    language: "Inglês",
    price: 59.9,
    ISBN: "978-0-13-235088-4",
    page_count: 464,
    release_date: "2008-08-01",
    stock_quantity: 50,
    image_url: "http://ecx.images-amazon.com/images/I/51oXyW8WQwL.jpg",
    authors: ["Robert C. Martin"],
    genres: ["Tecnologia", "Programação"],
    publishers: ["Prentice Hall"],
  },
  {
    title: "Head First Java, 2nd Edition",
    synopsis:
      "Uma introdução divertida e visual para aprender Java e orientação a objetos.",
    language: "Inglês",
    price: 72.9,
    ISBN: "978-0-596-00920-5",
    page_count: 720,
    release_date: "2005-02-19",
    stock_quantity: 40,
    image_url: "http://ecx.images-amazon.com/images/I/51a1RPCmv7L.jpg",
    authors: ["Kathy Sierra", "Bert Bates"],
    genres: ["Tecnologia", "Programação"],
    publishers: ["O'Reilly Media"],
  },
  {
    title: "The Linux Command Line",
    synopsis:
      "Uma introdução completa ao ambiente de linha de comando do Linux.",
    language: "Inglês",
    price: 45.9,
    ISBN: "978-1-59327-389-7",
    page_count: 480,
    release_date: "2012-01-11",
    stock_quantity: 35,
    image_url: "http://ecx.images-amazon.com/images/I/51XjnOV6TOL.jpg",
    authors: ["William Shotts"],
    genres: ["Tecnologia", "Sistemas Operacionais"],
    publishers: ["No Starch Press"],
  },
  {
    title: "A Mão e a Luva",
    synopsis:
      "Um romance que retrata dilemas amorosos e sociais do século XIX.",
    language: "Português",
    price: 25.0,
    ISBN: "978-85-359-0275-8",
    page_count: 160,
    release_date: "1874-01-01",
    stock_quantity: 20,
    image_url:
      "https://m.media-amazon.com/images/I/613D-uzZ8AL._AC_UF1000,1000_QL80_.jpg",
    authors: ["Machado de Assis"],
    genres: ["Literatura Brasileira", "Romance"],
    publishers: ["Editora 34"],
  },
  {
    title: "Harry Potter e a Pedra Filosofal",
    synopsis: "O começo da jornada mágica de Harry Potter no mundo dos bruxos.",
    language: "Português",
    price: 49.9,
    ISBN: "978-85-325-1747-3",
    page_count: 224,
    release_date: "1997-06-26",
    stock_quantity: 30,
    image_url: "https://m.media-amazon.com/images/I/81ibfYk4qmL.jpg",
    authors: ["J.K. Rowling"],
    genres: ["Fantasia", "Aventura"],
    publishers: ["Rocco"],
  },
  {
    title: "Harry Potter e a Câmara Secreta",
    synopsis: "Harry retorna para Hogwarts, onde enfrenta novos perigos.",
    language: "Português",
    price: 49.9,
    ISBN: "978-85-325-1748-0",
    page_count: 251,
    release_date: "1998-07-02",
    stock_quantity: 25,
    image_url: "https://m.media-amazon.com/images/I/81jbivNEVML.jpg",
    authors: ["J.K. Rowling"],
    genres: ["Fantasia", "Aventura"],
    publishers: ["Rocco"],
  },
  {
    title: "Harry Potter e o Prisioneiro de Azkaban",
    synopsis:
      "Harry descobre verdades sobre seu passado ao enfrentar Sirius Black.",
    language: "Português",
    price: 49.9,
    ISBN: "978-85-325-1749-7",
    page_count: 318,
    release_date: "1999-07-08",
    stock_quantity: 20,
    image_url: "https://m.media-amazon.com/images/I/81u+ljPVifL.jpg",
    authors: ["J.K. Rowling"],
    genres: ["Fantasia", "Aventura"],
    publishers: ["Rocco"],
  },
  {
    title: "Harry Potter e o Cálice de Fogo",
    synopsis:
      "Harry participa do Torneio Tribruxo e enfrenta desafios perigosos.",
    language: "Português",
    price: 59.9,
    ISBN: "978-85-325-1750-3",
    page_count: 636,
    release_date: "2000-07-08",
    stock_quantity: 15,
    image_url: "https://m.media-amazon.com/images/I/81nTLN-kz7L.jpg",
    authors: ["J.K. Rowling"],
    genres: ["Fantasia", "Aventura"],
    publishers: ["Rocco"],
  },
  {
    title: "Harry Potter e a Ordem da Fênix",
    synopsis: "Harry lidera um grupo de resistência contra Voldemort.",
    language: "Português",
    price: 59.9,
    ISBN: "978-85-325-1751-0",
    page_count: 702,
    release_date: "2003-06-21",
    stock_quantity: 15,
    image_url: "https://m.media-amazon.com/images/I/81d6ESyPZwL.jpg",
    authors: ["J.K. Rowling"],
    genres: ["Fantasia", "Aventura"],
    publishers: ["Rocco"],
  },
  {
    title: "Harry Potter e o Enigma do Príncipe",
    synopsis: "Harry e Dumbledore exploram memórias sobre Voldemort.",
    language: "Português",
    price: 59.9,
    ISBN: "978-85-325-1752-7",
    page_count: 512,
    release_date: "2005-07-16",
    stock_quantity: 10,
    image_url: "https://m.media-amazon.com/images/I/81yFIh1yoZL.jpg",
    authors: ["J.K. Rowling"],
    genres: ["Fantasia", "Aventura"],
    publishers: ["Rocco"],
  },
  {
    title: "Harry Potter e as Relíquias da Morte",
    synopsis: "Harry enfrenta a batalha final contra Voldemort.",
    language: "Português",
    price: 59.9,
    ISBN: "978-85-325-1753-4",
    page_count: 759,
    release_date: "2007-07-21",
    stock_quantity: 10,
    image_url:
      "https://m.media-amazon.com/images/I/81rvO7xcJOL._AC_UF1000,1000_QL80_.jpg",
    authors: ["J.K. Rowling"],
    genres: ["Fantasia", "Aventura"],
    publishers: ["Rocco"],
  },
  {
    title: "As Aventuras de Sherlock Holmes",
    synopsis:
      "Uma coletânea de contos sobre os casos mais intrigantes de Sherlock Holmes.",
    language: "Português",
    price: 39.9,
    ISBN: "978-85-359-1234-5",
    page_count: 320,
    release_date: "1892-10-14",
    stock_quantity: 25,
    image_url:
      "https://m.media-amazon.com/images/I/613LTnr4lgL._AC_UF1000,1000_QL80_.jpg",
    authors: ["Arthur Conan Doyle"],
    genres: ["Mistério", "Suspense"],
    publishers: ["Principis"],
  },
  {
    title: "O Cão dos Baskervilles",
    synopsis: "Sherlock Holmes investiga uma misteriosa maldição em Dartmoor.",
    language: "Português",
    price: 42.9,
    ISBN: "978-85-359-1235-2",
    page_count: 248,
    release_date: "1902-08-01",
    stock_quantity: 20,
    image_url:
      "https://m.media-amazon.com/images/I/619kzsBXy8L._AC_UF1000,1000_QL80_.jpg",
    authors: ["Arthur Conan Doyle"],
    genres: ["Mistério", "Suspense"],
    publishers: ["Principis"],
  },
  {
    title:
      "Brazilian Jiu-Jitsu: The Ultimate Guide to Dominating Brazilian Jiu-Jitsu and Mixed Martial Arts Combat",
    synopsis:
      "Um guia abrangente para dominar o Jiu-Jitsu Brasileiro e o combate de artes marciais mistas.",
    language: "Inglês",
    price: 26.0,
    ISBN: "804842752",
    page_count: 320,
    release_date: "2010-01-01",
    stock_quantity: 15,
    image_url: "http://ecx.images-amazon.com/images/I/51Dotkh6f2L.jpg",
    authors: ["Alexandre Paiva"],
    genres: ["Sports & Outdoors"],
    publishers: ["Victory Belt Publishing"],
  },
  {
    title: "No Limits (Hqn)",
    synopsis:
      "Uma história envolvente que explora desafios e paixão no mundo dos esportes.",
    language: "Inglês",
    price: 26.0,
    ISBN: "373779046",
    page_count: 384,
    release_date: "2014-08-26",
    stock_quantity: 20,
    image_url: "http://ecx.images-amazon.com/images/I/51oCp8JAz1L.jpg",
    authors: ["Lori Foster"],
    genres: ["Sports & Outdoors"],
    publishers: ["Harlequin Books"],
  },
  {
    title: "Parting the Clouds - The Science of the Martial Arts",
    synopsis:
      "Um guia para entender a ciência por trás dos golpes de artes marciais.",
    language: "Inglês",
    price: 26.0,
    ISBN: "983704104",
    page_count: 300,
    release_date: "2012-01-01",
    stock_quantity: 18,
    image_url: "http://ecx.images-amazon.com/images/I/51g13m-6dSL.jpg",
    authors: ["Mr. Grenville Harrop"],
    genres: ["Sports & Outdoors"],
    publishers: ["CreateSpace Independent Publishing"],
  },
  {
    title:
      "Mastering the Rubber Guard: Jiu Jitsu for Mixed Martial Arts Competition",
    synopsis:
      "Técnicas avançadas de guarda de borracha para competições de Jiu-Jitsu e MMA.",
    language: "Inglês",
    price: 26.0,
    ISBN: "977731596",
    page_count: 224,
    release_date: "2008-01-01",
    stock_quantity: 25,
    image_url: "http://ecx.images-amazon.com/images/I/5184uoh2alL.jpg",
    authors: ["Eddie Bravo"],
    genres: ["Sports & Outdoors"],
    publishers: ["Victory Belt Publishing"],
  },
  {
    title:
      "Muay Thai Counter Techniques: Competitive Skills and Tactics for Success",
    synopsis: "Estratégias e táticas para dominar o Muay Thai competitivo.",
    language: "Inglês",
    price: 26.0,
    ISBN: "1583945431",
    page_count: 200,
    release_date: "2013-01-08",
    stock_quantity: 20,
    image_url: "http://ecx.images-amazon.com/images/I/51rJPwbGbJL.jpg",
    authors: ["Christoph Delp"],
    genres: ["Sports & Outdoors"],
    publishers: ["Blue Snake Books"],
  },
  {
    title: "Training for Warriors: The Ultimate Mixed Martial Arts Workout",
    synopsis:
      "Um guia de treinamento intenso para guerreiros e atletas de MMA.",
    language: "Inglês",
    price: 26.0,
    ISBN: "61374334",
    page_count: 304,
    release_date: "2008-01-01",
    stock_quantity: 15,
    image_url: "http://ecx.images-amazon.com/images/I/618n5BaHmWL.jpg",
    authors: ["Martin Rooney"],
    genres: ["Sports & Outdoors"],
    publishers: ["HarperOne"],
  },
  {
    title:
      "Ultimate Warrior Workouts (Training for Warriors): Fitness Secrets of the Martial Arts",
    synopsis:
      "Segredos de condicionamento físico das artes marciais para treino e sucesso.",
    language: "Inglês",
    price: 26.0,
    ISBN: "61735221",
    page_count: 384,
    release_date: "2010-01-01",
    stock_quantity: 15,
    image_url: "http://ecx.images-amazon.com/images/I/61XTmArLdbL.jpg",
    authors: ["Martin Rooney"],
    genres: ["Sports & Outdoors"],
    publishers: ["HarperOne"],
  },
  {
    title: "UFC Encyclopedia",
    synopsis: "Um guia completo sobre a história e lutadores do UFC.",
    language: "Inglês",
    price: 26.0,
    ISBN: "756683610",
    page_count: 400,
    release_date: "2011-01-01",
    stock_quantity: 10,
    image_url: "http://ecx.images-amazon.com/images/I/51Zbpf5f9EL.jpg",
    authors: ["Thomas Gerbasi"],
    genres: ["Sports & Outdoors"],
    publishers: ["DK Publishing"],
  },
  {
    title: "Got Fight?: The 50 Zen Principles of Hand-to-Face Combat",
    synopsis: "Os princípios do combate direto com humor e sabedoria.",
    language: "Inglês",
    price: 26.0,
    ISBN: "61721727",
    page_count: 208,
    release_date: "2009-01-01",
    stock_quantity: 20,
    image_url: "http://ecx.images-amazon.com/images/I/51S1c54rL9L.jpg",
    authors: ["Forrest Griffin"],
    genres: ["Sports & Outdoors"],
    publishers: ["William Morrow Paperbacks"],
  },
  {
    title: "Jackson's Mixed Martial Arts: The Ground Game",
    synopsis: "Um guia focado em técnicas de combate no chão para MMA.",
    language: "Inglês",
    price: 26.0,
    ISBN: "982565801",
    page_count: 272,
    release_date: "2010-01-01",
    stock_quantity: 15,
    image_url: "http://ecx.images-amazon.com/images/I/5194nxULwGL.jpg",
    authors: ["Greg Jackson"],
    genres: ["Sports & Outdoors"],
    publishers: ["Victory Belt Publishing"],
  },
  {
    title: "Thrown",
    synopsis:
      "Uma exploração profunda das vidas de lutadores e do mundo do MMA.",
    language: "Inglês",
    price: 26.0,
    ISBN: "1936747928",
    page_count: 240,
    release_date: "2014-01-01",
    stock_quantity: 18,
    image_url: "http://ecx.images-amazon.com/images/I/41lECbFAJ7L.jpg",
    authors: ["Kerry Howley"],
    genres: ["Sports & Outdoors"],
    publishers: ["Sarabande Books"],
  },
  {
    title: "Fedor: The Fighting System of the World's Undisputed King of MMA",
    synopsis: "O sistema de luta do lendário lutador de MMA Fedor Emelianenko.",
    language: "Inglês",
    price: 26.0,
    ISBN: "977731545",
    page_count: 240,
    release_date: "2008-01-01",
    stock_quantity: 15,
    image_url: "http://ecx.images-amazon.com/images/I/51HIu-hYQAL.jpg",
    authors: ["Fedor Emelianenko"],
    genres: ["Sports & Outdoors"],
    publishers: ["Victory Belt Publishing"],
  },
  {
    title: "Caged Warrior",
    synopsis: "A jornada de um lutador em busca de redenção e triunfo.",
    language: "Inglês",
    price: 26.0,
    ISBN: "1423171241",
    page_count: 320,
    release_date: "2013-01-01",
    stock_quantity: 10,
    image_url: "http://ecx.images-amazon.com/images/I/51pjVYwBeXL.jpg",
    authors: ["Alan Lawrence Sitomer"],
    genres: ["Sports & Outdoors"],
    publishers: ["Disney-Hyperion"],
  },
  {
    title: "Mixed Martial Arts: The Book of Knowledge",
    synopsis: "Um guia definitivo sobre estratégias e técnicas de MMA.",
    language: "Inglês",
    price: 26.0,
    ISBN: "977731561",
    page_count: 304,
    release_date: "2007-01-01",
    stock_quantity: 20,
    image_url: "http://ecx.images-amazon.com/images/I/51iuBG3yPRL.jpg",
    authors: ["BJ Penn"],
    genres: ["Sports & Outdoors"],
    publishers: ["Victory Belt Publishing"],
  },
];
